# Generated by Django 6.0.1 on 2026-01-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_property_landlord_property_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('bedsitter', 'Bedsitter'), ('one_bedroom', '1 Bedroom'), ('two_bedroom', '2 Bedroom'), ('apartment', 'Apartment'), ('house', 'House'), ('shop', 'Shop')], max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='rent_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20),
        ),
    ]
